---
- name: Converge
  hosts: all

  pre_tasks:
  - name: "Install passlib"
    ansible.builtin.package:
      name: python3-pip
      state: present

  roles:
    - role: genlab.users
      definitions: "users.yaml"
      default_password: "def_pw.txt"

