---
users:
  - name: "user0"
    uid: 1001
    gid: 1004
    full_name: "User Zero"
    state: "present"
    groups: [sudo]
    create_home: true
    shell: "/bin/bash"
    pubkeys_file: "user0.keys"

  - name: "user1"
    uid: 1002
    gid: 1005
    full_name: "User One"
    state: "present"
    groups: []
    create_home: true
    shell: "/bin/sh"
    pubkeys_file: "user1.keys"
    password_lock: true
    expires: "2024-07-23 00:00:00"
