---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Get user info from /etc/passwd"
      register: passwd
      changed_when: false
      ansible.builtin.shell:
        cmd: set -o pipefail; cat /etc/passwd | grep user
        executable: /bin/bash

    - name: "Get user info from /etc/shadow"
      register: shadow
      changed_when: false
      ansible.builtin.shell:
        cmd: set -o pipefail; cat /etc/shadow | grep user
        executable: /bin/bash

    - name: "Verify expected account configuration"
      vars:
        expected_shadow:
          - "user0:$6$rounds=656000$himalayan$76YpfjVvtTktDi6nbIyVtCSkcX8V7Dz7KGOPkgCx/atCOQxTJL210hRWciLUyyzTpU0L9.MF6nlNB0SQR/hY5.:0:0:99999:7:::"
          - "user1:!$6$rounds=656000$himalayan$76YpfjVvtTktDi6nbIyVtCSkcX8V7Dz7KGOPkgCx/atCOQxTJL210hRWciLUyyzTpU0L9.MF6nlNB0SQR/hY5.:0:0:99999:7::19926:"
        expected_passwd:
          - "user0:x:1001:1004:User Zero:/home/user0:/bin/bash"
          - "user1:x:1002:1005:User One:/home/user1:/bin/sh"
      ansible.builtin.assert:
        that:
          - passwd.stdout_lines == expected_passwd
          - shadow.stdout_lines == expected_shadow
