---
- name: Converge
  hosts: all

  roles:
    - role: genlab.users
      def_pw_path: "def_pw.yml"
      manifest_path: "some-none-existent-file"  # 'users' is supposed to take precedence
      users:
        - name: "user0"
          uid: 1001
          gid: 1004
          full_name: "User Zero"
          state: "present"
          groups: [sudo]
          create_home: true
          shell: "/bin/bash"
          pubkeys_file: "user0.keys"

        - name: "user1"
          uid: 1002
          full_name: "User One"
          state: "present"
          groups: []
          create_home: true
          shell: "/bin/sh"
          password_lock: true
          expires: "2024-07-23 12:00:00"
