---
name: molecule
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  molecule:
    name: molecule
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: environment.yml
          init-shell: bash
          post-cleanup: 'all'

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        shell: micromamba-shell {0}
